### ISSUE TITLE
New to Risevision - Rise Player on Chromebox displaying white screen

### ISSUE THREAD

**Issue by cohoestech** [Rise-Vision/player-chromeapp#67]
Hello all,

I am new to Risevision and am looking at implementing this for our digital signage if it proves to be a solid platform.  So far, I haven't had much luck.  I've created a couple of Google Slides that were then saved as PNG files and saved to my Google Drive.  Created permalinks using gdURL and used those links to add the images into my presentation/placeholder.  I've set up the Chromebox display, added a schedule and published.  When I preview the presentation it appears fine and plays fine with the desired transitions.

However, on the Chromebox, I just see a blank white screen (background - if I change the background color or add an image, that appears), but the presentation never starts....

If I use the trial Risevision storage and upload the same PNG images that I've got saved in my Google Drive, it works fine....

Any help would be greatly appreciated.

Thanks!

**Comment by alanclayton** [comment]
@cohoestech we (Rise Vision) only support Rise Player on Windows, Linux and Raspbian at this time. https://goo.gl/mjOlRs

As for the images not appearing when you host on Drive, the share URL provided by Drive won't work https://www.screencast.com/t/X9p5YhYYd. You need to get the direct URL that goes to the image. I think you can get it by opening URL provided from Drive. Then right click on the image and select "Copy image address". Use this URL in the Widget instead of the share link.

Keep in mind Google could change this at anytime and we personally don't recommend using it for digital signage for that reason. 

Thanks!
